language: node_js
node_js:
  - lts/*
# https://stackoverflow.com/questions/42521884/should-i-have-travis-cache-node-modules-or-home-npm
cache:
  directories:
    - .npm
jobs:
  include:
    - stage: ci
      script:
        - npm run ci
    - stage: commitlint
      script:
        - commitlint-travis
    - stage: release
      if: branch = master
      script:
        - npm run semantic-release
deploy:
  provider: firebase
  token: "U+bFM3NmuIEOW/G3uIfqFVicwxQ0neewiYRuAoBP0QKmyp6T99cKympAaSlHdtwaoayReD0FSkSiwPxCfv+R62F0unKzWorZg/ZqmeVzPs5qNPuAa6hopWzbmsbwTUSh/zHKK2Rbrm7sYUB9+Q+5Z/0jrfE4PpbtsNIQbWH/VccP6kjNYeUO2oVrBiCwXR2KTwH/cGON4kbJv0TmmzMZyvN29pnQfadHEfBI2H8lm7xn9XPIstib0ZR7RUMkz7tPMt2bzvQy+tPMt1wVhdYTKBeucMQOva2BSO8/Hzv2KwblHZUCKm3oDQiyAvHwzdesUjq2gxXRH81cE5hqfWpYa3LkzzdelOxjtjc4rPHz7i9NxwAv6qb/wBfW8jEc6SGoa4caxokQATZr5FDNR5aAdsw3ZiOBg8rtjb+hnJpoMDX3xh5byq1kqiAz1yPyr0Dos2J5xN8MW/rEkVt45VJEM/fEwWpKMsj5+OfurOMk5Vcq1nw6sFwx0XxLYqkVarTdeODo8OmErPkJ2USFwdXmEhGv5hr+8KRL3p2JSlTMn4fyLcBNY1MjN1lf6qDfvbdpOSJTm+OaOL931L6iBlgWqkdFxM631L8oGlyquGUpDNDsyemnCu2GJj7CZ3obgL3Oqa9NbNBlg7h6QxjcjUfoi4II+42U5/GSXSSvhvxHm4s="
  project: react-hot-starter
  on:
    branch: master
  edge: true # opt in to dpl v2
deploy:
  provider: firebase
  token: "U+bFM3NmuIEOW/G3uIfqFVicwxQ0neewiYRuAoBP0QKmyp6T99cKympAaSlHdtwaoayReD0FSkSiwPxCfv+R62F0unKzWorZg/ZqmeVzPs5qNPuAa6hopWzbmsbwTUSh/zHKK2Rbrm7sYUB9+Q+5Z/0jrfE4PpbtsNIQbWH/VccP6kjNYeUO2oVrBiCwXR2KTwH/cGON4kbJv0TmmzMZyvN29pnQfadHEfBI2H8lm7xn9XPIstib0ZR7RUMkz7tPMt2bzvQy+tPMt1wVhdYTKBeucMQOva2BSO8/Hzv2KwblHZUCKm3oDQiyAvHwzdesUjq2gxXRH81cE5hqfWpYa3LkzzdelOxjtjc4rPHz7i9NxwAv6qb/wBfW8jEc6SGoa4caxokQATZr5FDNR5aAdsw3ZiOBg8rtjb+hnJpoMDX3xh5byq1kqiAz1yPyr0Dos2J5xN8MW/rEkVt45VJEM/fEwWpKMsj5+OfurOMk5Vcq1nw6sFwx0XxLYqkVarTdeODo8OmErPkJ2USFwdXmEhGv5hr+8KRL3p2JSlTMn4fyLcBNY1MjN1lf6qDfvbdpOSJTm+OaOL931L6iBlgWqkdFxM631L8oGlyquGUpDNDsyemnCu2GJj7CZ3obgL3Oqa9NbNBlg7h6QxjcjUfoi4II+42U5/GSXSSvhvxHm4s="
  project: react-hot-starter-dev
  on:
    branch: develop
  edge: true # opt in to dpl v2
