name: staging

on:
  pull_request:
    branches:
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install
        run: npm install
      - name: ci
        run: npm run ci
